#!/bin/bash"

## Activation des prérequis minimaux
systemctl daemon-reload

# whoamiREE
systemctl enable whoamiREE.service
systemctl start whoamiREE.service

# delroute
systemctl enable delroute.service
systemctl start delroute.service

# wpa_supplicant
systemctl stop wpa_supplicant.service
systemctl disable wpa_supplicant.service

systemctl start wpa_supplicant@wlan1.service
systemctl enable wpa_supplicant@wlan1.service
systemctl status wpa_supplicant@wlan1.service

# hostapd
systemctl unmask hostapd
systemctl enable hostapd
systemctl restart hostapd.service