#!/bin/bash -u

LOG_FILE="/var/log/REE.log"
log() {
    echo "$(date '+%Y-%m-%d %H:%M:%S') - $1" >> "$LOG_FILE"
}

# Activation du wifi
# sudo rfkill unblock wifi

sudo mkdir -p /usr/local/bin &> /dev/null
sudo mkdir -p /usr/local/templates &> /dev/null
sudo mkdir -p /usr/local/templates/node &> /dev/null
sudo mkdir -p /usr/local/templates/bridge &> /dev/null
sudo mkdir -p /usr/local/templates/gateway &> /dev/null

# sudo mv ../usr/local/bin/up-eth0 /etc/network/if-up.d/
# chmod +x /etc/network/if-up.d/up-eth0
sudo cp -R ../usr/local/* /usr/local/
chmod +x /usr/local/bin/*


# Installation des paquets
sudo apt-get install -y batctl
apt install espeak -y
sudo apt-get install -y dnsmasq
sudo apt-get install -y bridge-utils


# Commun
sudo cp /usr/local/templates/wlan0 /etc/network/interfaces.d/wlan0
# sudo cp /usr/local/templates/rc.local /etc/rc.local


# Systemd
sudo cp ../etc/systemd/system/* /etc/systemd/system

# Hook
sudo cp ../etc/dhcpcd.exit-hook /etc/dhcpcd.exit-hook


# Service qui supprime les route créer par hostpad
log "Creation du service delroute"
cat  ../etc/systemd/system/delroute.service > /etc/systemd/system/delroute.service
